kind: Namespace
apiVersion: v1
metadata:
  name: dev
---
kind: Namespace
apiVersion: v1
metadata:
  name: stage
---
kind: Namespace
apiVersion: v1
metadata:
  name: preprod
---
kind: Namespace
apiVersion: v1
metadata:
  name: allan
